agent: pi
environment: docker-python3.12-uv
prompt: just-solve
model:
  provider: aqueduct
  name: deepseek-v4-vision-exp
thinking: max
save_template: ${model.name}/${agent.type}-${agent.version}_${prompt}_${thinking}
